version: '3'

services:
  database:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
      args:
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_NAME=${DB_NAME}
    ports:
      - "6010:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  file-server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "6020:4321"
    volumes:
      - ./uploads:/uploads

  message-broker:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
      args:
        - MB_PASSWORD=${MB_PASSWORD}
        - MB_USER=${MB_USER}
    ports:
      - "6030:5672"
      - "16030:15672"
