spring:
  application:
    name: automarket24-backend

  config:
    import: file:.env.properties

  devtools:
    restart:
      log-condition-evaluation-delta: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    secret-key: ${SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  rabbitmq:
    port: 6030
    username: user
    password: password

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /api-docs-ui.html
    operations-sorter: method