spring:
  application:
    name: automarket24-backend

  config:
    import: file:.env.properties

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    secret-key: ${SECRET_KEY}

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /api-docs-ui.html
    operations-sorter: method