spring:
  application:
    name: automarket24-backend

  config:
    import: file:.env.properties

  devtools:
    restart:
      log-condition-evaluation-delta: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:6010/automarket24
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    secret-key: ${SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: ${EM_HOST}
    port: 587
    username: ${EM_USERNAME}
    password: ${EM_PASSWORD}

  rabbitmq:
    port: 6030
    username: ${MB_USERNAME}
    password: ${MB_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /api-docs-ui.html
    operations-sorter: method